### PR TITLE
Added Video Converter & Audio Converter

### PR DESCRIPTION
**Pull request by osaleem303**

### CODE REVIEW

**Review by jfversluis — CHANGES_REQUESTED** [review]
Can you please add them in alphabetical order?

also this is amazing! 🤩

**Comment by osaleem303** [comment]
@jfversluis Thank you!
Yes, I have made changes by Alphabetical order

**Comment by osaleem303** [comment]
@jfversluis 
Do let me know if you want to try & review the app, I'll send you promo.

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
I would love that! Find my email on my GitHub profile please!

**Comment by osaleem303** [comment]
> I would love that! Find my email on my GitHub profile please!

Done! I've sent you promos on your email.

**Pull request merged**
